import os
from datetime import datetime

# Define the output file
output_file = 'README.md'

# Define the disclaimer text
disclaimer = """
# Testing Repository

**Disclaimer: This repository is STRICTLY for testing purposes ONLY. Any content contained within it is ABSOLUTELY not to be considered as final or production-ready. I do not take any responsibility or ownership of anything in this repository. USE AT YOUR OWN RISK.**
"""

def generate_readme(directory):
    # Start with a header
    content = "# Directory Listing\n\n"
    content += "This is an autogenerated list of files in the current directory.\n\n"

    # Add the list of files
    for item in sorted(os.listdir(directory)):
        if os.path.isfile(os.path.join(directory, item)):
            content += f"- [{item}](./{item})\n"

    # Add the generation timestamp
    content += f"\n*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n"

    # Add the disclaimer
    content += disclaimer

    # Write to the README.md file
    with open(output_file, 'w') as f:
        f.write(content)

if __name__ == "__main__":
    generate_readme(os.getcwd())