#!/bin/bash

# Define the output file
output="README.md"

# Write the header to the README.md
echo "# Directory Listing" > "$output"
echo "" >> "$output"
echo "This is an autogenerated list of files in the current directory." >> "$output"
echo "" >> "$output"

# Iterate over each item in the current directory
for item in *; do
    # Check if the item is a file
    if [ -f "$item" ]; then
        echo "- [${item}](./${item})" >> "$output"
    fi
done

echo "" >> "$output"
echo "Generated on $(date)" >> "$output"